# Likert single stimulus page 3 stimuli, 2 responses

testname: Likert Single Simulus with two responses
testId: lss_2scale
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
  - type: likert_single_stimulus
    id: lss1
    name: likert
    content: test description
    mustPlayback: processUpdate
    stimuli:
      C1: configs/resources/audio/mono_c1.wav
      C2: configs/resources/audio/mono_c2.wav
      C3: configs/resources/audio/mono_c3.wav
    questionnaire:
      - type: likert
        name: likert-question
        response:
          - value: not at all
            label: Not at all
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
          - value: not a lot
            label: Not a lot
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
      - type: text
        name: text-question
        label: text
      - type: number
        name: number-question
        label: number
      - type: date
        name: date-question
        label: date
      - type: long_text
        name: long_text-question
        label: long text
      - type: toggle
        name: toggle-question
        label: toggle
        response:
          - value: no
            label: no
          - value: yes
            label: yes
      - type: checkbox
        name: checkbox-question
        label: checkbox
        optional: true

  - type: finish
    name: Thank you
    content: Thank you for attending
    showResults: true
    writeResults: true
